[package]
name = "arb-portfolio"
version = "1.0.0"
authors = ["Ryan Bruno <ryanbruno506@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
log4rs = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1"

